name: Lint

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: actions/checkout@v3
      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m